#!/usr/bin/env php
<?php

// artisan
// Laravel command-line interface entry point.
// Usage inside Docker: docker compose exec php-fpm php artisan <command>

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Composer autoloader
require __DIR__.'/vendor/autoload.php';

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
